# DynamoDB TripTable
tripTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: "tripTable"
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "userId"
        AttributeType: "S"
      - AttributeName: "tripId"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "userId"
        KeyType: "HASH"
      - AttributeName: "tripId"
        KeyType: "RANGE"

# Dynamodb MessageTable
messageTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: "messageTable"
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "messageId"
        AttributeType: "S"
      - AttributeName: "tripId"
        AttributeType: "S"
      - AttributeName: "createdAt"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "messageId"
        KeyType: "HASH"
    GlobalSecondaryIndexes:
      - IndexName: "messagesByTrip"
        KeySchema: 
          - AttributeName: "tripId"
            KeyType: "HASH"
          - AttributeName: "createdAt"
            KeyType: "RANGE"
        Projection:
          ProjectionType: ALL

# Cognito User Pool
cognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: "inukUserPool"
    UsernameAttributes:
      - email

# Cognito User Pool Client
cognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: inukUserPoolClient
    UserPoolId: !Ref cognitoUserPool
