service: inuk-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2

plugins: 
  - serverless-appsync-plugin
  # - serverless-iam-roles-per-function
  

custom: 
  stage: ${opt:stage, self:provider.stage}
  appSync: 
    - ${file(appsync.yml)}

resources: 
  Resources: 
    ${file(resources.yml)}